/****************************************************************************************
		Conway's Game of Life Implemented in T-SQL
		Ver. 0.2 (alpha) proof-of-concept
		Copyright 2016 Eric Shultz
		Date: 11/2/2016

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*****************************************************************************************/

USE [master]
GO

/****** Object:  Database [Life]    Script Date: 11/2/2016 1:44:36 AM ******/
CREATE DATABASE [Life]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Life', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Life.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Life_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Life_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Life] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Life].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Life] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Life] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Life] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Life] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Life] SET ARITHABORT OFF 
GO

ALTER DATABASE [Life] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Life] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Life] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Life] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Life] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Life] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Life] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Life] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Life] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Life] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Life] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Life] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Life] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Life] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Life] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Life] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Life] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Life] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Life] SET  MULTI_USER 
GO

ALTER DATABASE [Life] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Life] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Life] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Life] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Life] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Life] SET QUERY_STORE = OFF
GO

USE [Life]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Life] SET  READ_WRITE 
GO


